theme: minima

title: Farzam Arefi
description: Machine Learning & AI Engineer
url: "https://gitFarzam.github.io"

plugins:
  - jekyll-feed

markdown: kramdown

# Dark mode support
minima:
  skin: dark
